[build]
  base = ""
  publish = ".next"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200
  force = true
 